# Generated by Django 5.0.2 on 2024-05-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokter_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='dokter_id',
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='hours_worked',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='hours_worked',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.DeleteModel(
            name='DokterResult',
        ),
    ]
