# Generated by Django 5.0.2 on 2024-05-16 16:02

from django.db import migrations, models


def set_default_hours_worked(apps, schema_editor):
    Attendance = apps.get_model('dokter_management_app', 'Attendance')
    Attendance.objects.filter(hours_worked__isnull=True).update(hours_worked=0.0)

class Migration(migrations.Migration):

    dependencies = [
        ('dokter_management_app', '0002_remove_subjects_dokter_id_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_hours_worked),
    ]
