# Generated by Django 5.0.2 on 2024-05-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokter_management_app', '0003_set_default_hours_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokters',
            name='courses',
            field=models.ManyToManyField(related_name='dokters_courses', to='dokter_management_app.courses'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
