# Generated by Django 5.0.2 on 2024-05-21 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokter_management_app', '0004_dokters_courses_alter_courses_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokters',
            name='courses',
        ),
    ]
