# Generated by Django 5.0.2 on 2024-05-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokter_management_app', '0005_remove_dokters_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancereport',
            name='hours_worked',
        ),
    ]
