
from django.urls import path, include
from . import views
from .import HodViews, DokterViews


urlpatterns = [
    path('', views.loginPage, name="login"),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('doLogin/', views.doLogin, name="doLogin"),
    path('get_user_details/', views.get_user_details, name="get_user_details"),
    path('logout_user/', views.logout_user, name="logout_user"),
    path('admin_home/', HodViews.admin_home, name="admin_home"),
    path('add_course/', HodViews.add_course, name="add_course"),
    path('add_course_save/', HodViews.add_course_save, name="add_course_save"),
    path('manage_course/', HodViews.manage_course, name="manage_course"),
    path('edit_course/<course_id>/', HodViews.edit_course, name="edit_course"),
    path('edit_course_save/', HodViews.edit_course_save, name="edit_course_save"),
    path('delete_course/<course_id>/', HodViews.delete_course, name="delete_course"),
    path('manage_session/', HodViews.manage_session, name="manage_session"),
    path('add_session/', HodViews.add_session, name="add_session"),
    path('add_session_save/', HodViews.add_session_save, name="add_session_save"),
    path('edit_session/<session_id>', HodViews.edit_session, name="edit_session"),
    path('edit_session_save/', HodViews.edit_session_save, name="edit_session_save"),
    path('delete_session/<session_id>/', HodViews.delete_session, name="delete_session"),
    path('add_dokter/', HodViews.add_dokter, name="add_dokter"),
    path('add_dokter_save/', HodViews.add_dokter_save, name="add_dokter_save"),
    path('edit_dokter/<dokter_id>', HodViews.edit_dokter, name="edit_dokter"),
    path('edit_dokter_save/', HodViews.edit_dokter_save, name="edit_dokter_save"),
    path('manage_dokter/', HodViews.manage_dokter, name="manage_dokter"),
    path('delete_dokter/<dokter_id>/', HodViews.delete_dokter, name="delete_dokter"),
    path('add_subject/', HodViews.add_subject, name="add_subject"),
    path('add_subject_save/', HodViews.add_subject_save, name="add_subject_save"),
    path('manage_subject/', HodViews.manage_subject, name="manage_subject"),
    path('edit_subject/<subject_id>/', HodViews.edit_subject, name="edit_subject"),
    path('edit_subject_save/', HodViews.edit_subject_save, name="edit_subject_save"),
    path('delete_subject/<subject_id>/', HodViews.delete_subject, name="delete_subject"),
    path('check_email_exist/', HodViews.check_email_exist, name="check_email_exist"),
    path('check_username_exist/', HodViews.check_username_exist, name="check_username_exist"),
    path('dokter_feedback_message/', HodViews.dokter_feedback_message, name="dokter_feedback_message"),
    path('dokter_feedback_message_reply/', HodViews.dokter_feedback_message_reply, name="dokter_feedback_message_reply"),
    path('dokter_leave_view/', HodViews.dokter_leave_view, name="dokter_leave_view"),
    path('dokter_leave_approve/<leave_id>/', HodViews.dokter_leave_approve, name="dokter_leave_approve"),
    path('dokter_leave_reject/<leave_id>/', HodViews.dokter_leave_reject, name="dokter_leave_reject"),
    path('admin_view_attendance/', HodViews.admin_view_attendance, name="admin_view_attendance"),
    path('admin_view_gaji/', HodViews.admin_view_gaji, name="admin_view_gaji"),
    path('admin_get_attendance_dates/', HodViews.admin_get_attendance_dates, name="admin_get_attendance_dates"),
    path('admin_get_attendance_dokter/', HodViews.admin_get_attendance_dokter, name="admin_get_attendance_dokter"),
    path('admin_profile/', HodViews.admin_profile, name="admin_profile"),
    path('admin_profile_update/', HodViews.admin_profile_update, name="admin_profile_update"),

    # URSL for Dokter
    path('dokter_home/', DokterViews.dokter_home, name="dokter_home"),
    path('dokter_take_attendance/', DokterViews.dokter_take_attendance, name="dokter_take_attendance"),
    path('get_dokters/', DokterViews.get_dokters, name="get_dokters"),
    path('save_attendance_data/', DokterViews.save_attendance_data, name="save_attendance_data"),
    path('dokter_update_attendance/', DokterViews.dokter_update_attendance, name="dokter_update_attendance"),
    path('get_attendance_dates/', DokterViews.get_attendance_dates, name="get_attendance_dates"),
    path('get_attendance_dokter/', DokterViews.get_attendance_dokter, name="get_attendance_dokter"),
    path('update_attendance_data/', DokterViews.update_attendance_data, name="update_attendance_data"),
    path('dokter_view_attendance/', DokterViews.dokter_view_attendance, name="dokter_view_attendance"),
    path('dokter_view_attendance_post/', DokterViews.dokter_view_attendance_post, name="dokter_view_attendance_post"),
    path('dokter_apply_leave/', DokterViews.dokter_apply_leave, name="dokter_apply_leave"),
    path('dokter_apply_leave_save/', DokterViews.dokter_apply_leave_save, name="dokter_apply_leave_save"),
    path('dokter_feedback/', DokterViews.dokter_feedback, name="dokter_feedback"),
    path('dokter_feedback_save/', DokterViews.dokter_feedback_save, name="dokter_feedback_save"),
    path('dokter_profile/', DokterViews.dokter_profile, name="dokter_profile"),
    path('dokter_profile_update/', DokterViews.dokter_profile_update, name="dokter_profile_update")
]
